# Generated by Django 5.0.7 on 2024-08-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_watchesuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='image',
            field=models.ImageField(default='all_images/w_5.png', upload_to='all_images/'),
        ),
    ]
