# Generated by Django 5.0.7 on 2024-09-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_accessory_alter_processor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='details',
            field=models.TextField(default='coming soon'),
        ),
    ]
